# Generated by Django 4.1 on 2023-05-31 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                ("title", models.CharField(max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=50)),
                ("date", models.DateField()),
                (
                    "id",
                    models.IntegerField(
                        max_length=100, primary_key=True, serialize=False
                    ),
                ),
            ],
        ),
    ]
